### ISSUE TITLE
The document is so poor that I couldn't install successfully

### ISSUE THREAD

**Issue by liushuaikobe** [dbrain/ckeditor-syntaxhighlight#4]
Like what the title said.
I watch the doc for CKEditor for 3.X, and do as which said, but it doen't work on CKEditor 4.X.

**Comment by tristanjahier** [comment]
Are you talking about documentation ? If so, do you talk about the CKEditor official docs ?
This repo only contains a plugin for CKEditor, and it's not supposed to provide documentation for CKEditor installation.

But if you try to install this plugin into CKEditor, just copy the folder "syntaxhighlight" and paste-it into the "plugins" directory of CKEditor.

**Comment by sziegltrum** [comment]
Depending on your configuration you have to add syntaxhighlighter to extraPlugins in your config-file (http://docs.ckeditor.com/#!/api/CKEDITOR.config) aditionally, but as tristanjahier said it's not a syntaxhighlighter-specific thing.

**Comment by liushuaikobe** [comment]
You mean how to modify the CKEditor's config file is none of this plugin's documents' business?
But I just copy this plugin into the "plugins" directory of CKEditor, and reload my html page, the syntaxhighlight plugin doesn't work(I can't find the button of inserting some codes)!!
As far as I'm concerned, If how to modify the CKEditor's config file to make the plugin work is mentioned in this repo's README, some new to CKEditor and plugins can't appreciate more.

**Comment by tristanjahier** [comment]
As @sziegltrum said, you'll have to watch the CKEditor documentation, particularly for plugins.
http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-extraPlugins

In your config file, you should have something like that :
`config.extraPlugins = 'syntaxhighlight';`

... in order to load the SyntaxHighlighter plugin for CKEditor.

Plugins installation is standardized, and so we're not supposed to explicitely precise it in here.
